version: 2

jobs:

  build:
    branches:
      only:
        - prod
    docker:
      - image: circleci/python:2.7.13
    working_directory: ~/earth
    steps:
      - checkout

  build_deploy_deps:
    docker:
      - image: circleci/python:2.7.13
    working_directory: ~/earth
    steps:
      - checkout
      - run: ls -la
      - run:
          name: Pull in the pips
          command: |
            virtualenv daenv
            . daenv/bin/activate
            pip install test-repo/.circle/requirements.txt

  # Put some tests in here
  test:
    docker:
      - image: circleci/python:2.7.13
    working_directory: ~/earth
    steps:
      - run: "true"

  deploy:
    docker:
      - image: circleci/python:2.7.13
    working_directory: ~/earth
    steps:
      - run: pip freeze
      - run:
          name: Run Script
          command: /bin/bash test-repo/test/echo.sh

workflows:
  version: 2

  prod:
    jobs:
      - build_deploy_deps:
          filters:
            branches:
              only:
                - prod
