version: 2

jobs:
  build:
    branches:
      only:
        - prod
    docker:
      - image: circleci/python:2.7.13
    steps:
      - run:
          name: "Nothing"
          command: "true"
  test:
    branches:
      only:
        - prod
    docker:
      - image: circleci/python:2.7.13
    steps:
      - run:
          name: "Nothing"
          command: "true"
