version: 2

jobs:

  build:
    branches:
      only:
        - prod
    docker:
      - image: circleci/python:2.7.13
    steps:
      - run:
          name: Install deps
          command: pip install pyOpenSSL ndg-httpsclient pyasn1 boto3 pytz
      - run: pip freeze

  test:
    branches:
      only:
        - prod
    docker:
      - image: circleci/python:2.7.13
    steps:
      - run: "true"

  deploy:
    branches:
      only:
        - prod
    docker:
      - image: circleci/python:2.7.13
    steps:
      - run:
          name: Display pip packages
          command: pip freeze
