version: 2

jobs:

  build:
    branches:
      only:
        - prod
    docker:
      - image: circleci/python:2.7.13
    working_directory: ~/test-repo
    steps:
      - checkout

  pull_deploy_deps:
    docker:
      - image: circleci/python:2.7.13
    working_directory: ~/test-repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-daenv-{{ checksum ".circleci/requirements.txt" }}
      - run:
          name: Pull in the pips
          command: |
            virtualenv daenv
            . daenv/bin/activate
            pip install -r .circleci/requirements.txt
      - save_cache:
          key: v1-daenv-{{ checksum ".circleci/requirements.txt" }}
          paths:
            - daenv

  # Put some tests in here
  test:
    docker:
      - image: circleci/python:2.7.13
    working_directory: ~/test-repo
    steps:
      - run: "true"

  deploy:
    docker:
      - image: circleci/python:2.7.13
    working_directory: ~/test-repo
    steps:
      - run: pip freeze
      - run:
          name: Run Script
          command: /bin/bash test-repo/test/echo.sh

workflows:
  version: 2

  prod:
    jobs:
      - pull_deploy_deps:
          filters:
            branches:
              only:
                - prod
