version: 2

jobs:

  build:
    docker:
      - image: circleci/node:4
    working_directory: ~/iflipd-app
    steps:
      - checkout
      # npm
      - restore_cache:
          keys:
            - v1-node-modules_{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-node-modules_{{ checksum "package.json" }}
          paths:
            - node_modules
      # bower
      - restore_cache:
          keys:
            - v1-bower-components_{{ checksum "bower.json" }}
      - run: node_modules/.bin/bower install --save
      - save_cache:
          key: v1-bower-components_{{ checksum "bower.json" }}
          paths:
            - bower_components

  # TODO Put some tests in here
  test:
    docker:
      - image: circleci/node:4
    working_directory: ~/iflipd-app
    steps:
      - run: "true"

  deploy:
    docker:
      - image: circleci/node:4
    working_directory: ~/iflipd-app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-node-modules_{{ checksum "package.json" }}
      - restore_cache:
          keys:
            - v1-bower-components_{{ checksum "bower.json" }}
      - run: node_modules/.bin/ember deploy production --verbose --activate=true

workflows:
  version: 2

# TODO can be enabled to do tests on all (or some) branches except for master
#  build-and-test:
#    jobs:
#      - build:
#          filters:
#            branches:
#              ignore: master
#      - test:
#          requires:
#            - build
#          filters:
#            branches:
#              ignore: master

  production-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
